apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  # downscale for non-work hours
  EXCLUDE_NAMESPACES: '{{- join "," .Values.excludedNamespaces }}'
  {{- if .Values.extraConfig }}
  {{- tpl .Values.extraConfig . | nindent 2 }}
  {{- end }}