# https://github.com/marketplace/actions/expire-action
on:
  schedule:
    - cron: "10 6 * * *"

name: Expire container tags

jobs:
  expire-tags:
    runs-on: ubuntu-latest
    name: "expire-tags"
    steps:
      - uses: eumel8/expire-action@1.0.2
        with:
          token: ${{secrets.TAGEXPIRE}}
          repo_type: org
          orgname: caas-team
          image_name: py-kube-downscaler
          protected_tags_regex: "^(latest|dev|[0-9][0-9]\\.\\d+\\.\\d+)$"
          days_treshold: 60
